// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.12.0'
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
    }
}

allprojects {
    repositories {
        google()
    }
}

ext {
    versionName = '2.5.0'
    versionCode = 25005
    minSdkVersion = 21
    compileSdkVersion = 29
    targetSdkVersion = 29
}
