name: MobSF Scan

on:
  push:
    branches: [ 2.0 ]
  pull_request:
    branches: [ 2.0 ]

  workflow_dispatch:

jobs:
  mobile-security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: wwwjdic --sarif --output results.sarif || true

      - name: Upload mobsfscan report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
